# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 23d234e7e5640f3070ee057d2e0a2810bab5d9ddab7f81d3b62e38be313008ff2ff64c000ab0619c30f571b79ac444edb4fc9ce98d2c683bf6481258d0aea9cf

test:
  secret_key_base: 7bc7326142abef52d5ce7eae7e086f58360149430d4c0e64fd0a779670b0d152893517fa94c00ba32cb4a5e5d6a08e45b0940fe1f61ccdb1cf97ae685582c620

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
